from tkinter import *
window=Tk()
window.title("my profile card")
window.geometry("400x500")
title=Label(window, text="My Profile Card", fg="white",bg="purple",width=40)
title.grid(row=0, column=0, columnspan=2, padx=10,pady=10)
name_label=Label(window, text="Name", fg="black",bg="white")
name_label.grid(row=1,column=0,padx=10,pady=10)
name_entry=Entry(window,fg="white",bg="purple",width=40)
name_entry.grid(row=1, column=1, padx=10,pady=10)
hobby_label=Label(window, text="Hobby", fg="black",bg="white")
hobby_label.grid(row=2,column=0,padx=10,pady=10)
hobby_entry=Entry(window,fg="white",bg="purple",width=40)
hobby_entry.grid(row=2, column=1, padx=10,pady=10)
submit=Button(window,text="Show my card",fg="white",bg="purple",width=20)
submit.grid(row=4,column=0,columnspan=2,padx=10,pady=10)
window.mainloop()